import  { test, expect } from '@playwright/test'
test ("Playwright Basics Marathon Program 2", async({page})=>{

    await page.goto("https://www.decathlon.in/")
    await page.waitForTimeout(3000)
    await page.locator("(//span[contains(text(),'Search')])[1]").click()
    const searchBox = page.getByPlaceholder("Search For 60+ Sports and 6000+ Products")
    expect(searchBox).toBeEnabled()
    await searchBox.click()
    await searchBox.fill("shoes")
    await searchBox.press('Enter')    
    await page.waitForTimeout(3000)
    const pageTitle = await page.title()
    console.log(pageTitle)
    expect(pageTitle).toEqual("Search | shoes")
    await page.locator("//div/span[text()='Sport']/following-sibling::ul/li/span[contains(text(),'Running')]").click()
    await page.locator("//div/span[text()='Gender']/following-sibling::ul/li/span[contains(text(),'Men')]").click()
    await page.locator("//div/span[text()='Size']/following-sibling::ul/li/span[contains(text(),'Uk 10.5')]").click()
    await page.getByAltText("Sorting").nth(1).click()
    await page.locator("//a[text()='Price: High to Low']").click()
    await page.locator("(//ul/li/div/div/div[2])[1]").click()
    await page.waitForTimeout(4000)
    await page.locator("//div[contains(text(),'10.5')]").click()
    await page.locator("//span[text()='ADD TO CART']").click()
    await page.waitForTimeout(4000)
    await page.locator("//p[text()='Cart']").click()
    const total_val= await page.locator("//div[@data-test-Id='cart:cart-checkout-total-cart-value']/p").innerText()    
    console.log("Total amount in the cart is :" +total_val)

})
